language: python

sudo: required

services:
 - docker

env:
  global:
    - IMAGE_NAME=flask-example
    - CONTAINER_NAME=flask-test
    - DOCKER_VERSION="1.9.1-0~trusty"

before_install:
  - sudo apt-get update
  - sudo apt-get remove docker-engine -yq
  - sudo apt-get install docker-engine=$DOCKER_VERSION -yq --no-install-suggests --no-install-recommends --force-yes -o Dpkg::Options::="--force-confnew"

services:
  - docker

script:
  - bash test_docker.sh
  - curl -i 0.0.0.0:8080
